global:
  applicationName: minio 
  customerName: placeholder
  impactLevel: placeholder
  environment: placeholder

microservices:
  virusscan:
    statefulset:
      enabled: true
    image:
      repository: registry.gamewarden.io/ironbank-proxy/ironbank/opensource/clamav/clamav
      tag: "1.0.1"
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1066
      runAsGroup: 1066
      fsGroup: 1066
