global:
  applicationName: test
  customerName: customerName
  impactLevel: il2
  environment: prd
  destinationCluster: in-cluster
  image:
    defaultImageRegistry: ghcr.io
    defaultImageRepository: second-front
argocd:
  wrapperAppOff: false
  sourceNamespaces:
  - "test"
  - "argocd"
  - "gw"
  projectOverride: "default"
  disableProjectCreation: true
default:
  virtualService:
    enabled: true

microservices:
  hackathon:
    image:
      pullPolicy: Always
    service:
      type: ClusterIP
      targetPort: 3000
    match:
      - uri:
          prefix: /