global:
  applicationName: test
  customerName: customerName
  impactLevel: il2
  environment: prd
  destinationCluster: in-cluster
  image:
    defaultImageRegistry: ghcr.io
    defaultImageRepository: second-front
argocd:
  wrapperAppOff: true
  sourceNamespaces:
  - "test"
  - "argocd"
  - "gw"
  projectOverride: "default"
  disableProjectCreation: true

microservices:
  hackathon:
    image:
      pullPolicy: Always
    service:
      targetPort: 3000
    match:
      - uri:
          prefix: /

manifests:
  hackathonVS:
    apiVersion: networking.istio.io/v1
    kind: VirtualService
    metadata:
      name: hackathon
    spec:
      gateways:
      - istio-system/public
      hosts:
      - hackathon.gw.local
      http:
      - route:
        - destination:
            host: hackathon
            port:
              number: 80