flux:
  interval: 2m
  rollback:
    cleanupOnFail: false

networkPolicies:
  enabled: false

kiali:
  enabled: false

istio:
  sourceType: helmRepo
  enabled: true

istioOperator:
  sourceType: helmRepo
  enabled: true

monitoring:
  sourceType: helmRepo
  enabled: true
  values:
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 200m
            memory: 1Gi

loki:
  sourceType: helmRepo
  enabled: true
  strategy: scalable
  values:
    minio:
      enabled: true
    write:
      replicas: 1
      persistence:
        size: 2Gi
      resources:
        limits:
          cpu: 200m
          memory: 400Mi
        requests:
          cpu: 200m
          memory: 400Mi
    read:
      replicas: 1
      persistence:
        size: 2Gi
      resources:
        limits:
          cpu: 200m
          memory: 400Mi
        requests:
          cpu: 200m
          memory: 400Mi
    extraobjects:
    - apiVersion: "security.istio.io/v1beta1"
      kind: PeerAuthentication
      metadata:
        name: loki-minio-endpoint-exception
        namespace: logging
      spec:
        mtls:
          mode: STRICT
        selector: 
          matchLabels:
            app: minio
        portLevelMtls:
          "9000":
            mode: PERMISSIVE
promtail:
  sourceType: helmRepo
  enabled: true

kyverno:
  sourceType: helmRepo
  enabled: true

kyvernoPolicies:
  sourceType: helmRepo
  enabled: true

neuvector:
  sourceType: helmRepo
  enabled: false
  values:
    k3s:
      enabled: true

addons:
  argocd:
    enabled: true
  metricsServer:
    sourceType: helmRepo
    enabled: auto
    values:
      args:
      - --kubelet-insecure-tls

  minioOperator:
    sourceType: helmRepo
    enabled: true