flux:
  interval: 2m
  rollback:
    cleanupOnFail: false

networkPolicies:
  enabled: false

kiali:
  enabled: false

istio:
  sourceType: helmRepo
  enabled: true

istioOperator:
  sourceType: helmRepo
  enabled: true

monitoring:
  sourceType: helmRepo
  enabled: true
  values:
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 200m
            memory: 1Gi

loki:
  sourceType: helmRepo
  enabled: true
  strategy: scalable
  values:
    minio:
      enabled: true
    write:
      replicas: 1
      persistence:
        size: 2Gi
      resources:
        limits:
          cpu: 200m
          memory: 400Mi
        requests:
          cpu: 200m
          memory: 400Mi
    read:
      replicas: 1
      persistence:
        size: 2Gi
      resources:
        limits:
          cpu: 200m
          memory: 400Mi
        requests:
          cpu: 200m
          memory: 400Mi
    extraobjects:
    - apiVersion: "security.istio.io/v1beta1"
      kind: PeerAuthentication
      metadata:
        name: loki-minio-endpoint-exception
        namespace: logging
      spec:
        mtls:
          mode: STRICT
        selector: 
          matchLabels:
            app: minio
        portLevelMtls:
          "9000":
            mode: PERMISSIVE
promtail:
  sourceType: helmRepo
  enabled: true

kyverno:
  sourceType: helmRepo
  enabled: true

kyvernoPolicies:
  sourceType: helmRepo
  enabled: true
  values:
    policies:
      restrict-volume-types:
        validationFailureAction: Audit
      restrict-image-registries:
        validationFailureAction: Audit
      restrict-host-path-write:
        validationFailureAction: Audit
      restrict-host-path-mount:
        validationFailureAction: Audit
      require-non-root-user:
        validationFailureAction: Audit
      require-non-root-group:
        validationFailureAction: Audit
      disallow-privileged-containers:
        validationFailureAction: Audit
      require-drop-all-capabilities:
        validationFailureAction: Audit
      restrict-host-path-mount-pv:
        validationFailureAction: Audit
neuvector:
  sourceType: helmRepo
  enabled: false
  values:
    k3s:
      enabled: true

addons:
  argocd:
    enabled: true
    values:
      server:
        extraArgs:
        - --insecure
        - --repo-server-plaintext
      repoServer:
        extraArgs:
        - --disable-tls
      controller:
        extraArgs:
        - --repo-server-plaintext
      redis:
        values: 
          networkPolicies:
            enabled: false
        networkPolicies:
          enabled: false
      redis-bb:
        values: 
          networkPolicies:
            enabled: false
        networkPolicies:
          enabled: false
      argocd-apps:
        applications:
          - destination:
              namespace: gw
              server: https://kubernetes.default.svc
            ignoreDifferences:
              - jsonPointers:
                  - /data
                  - /stringData
                kind: Secret
                name: generated-secrets
                namespace: gw

            name: gamewarden-app-prd
            namespace: argocd
            project: default
            sources:
              - helm:
                  valueFiles:
                    - $values/app/base.yaml
                    - $values/app/prd.yaml
                path: ./
                repoURL: https://github.com/second-front/uchart.git
                targetRevision: 1.0.10
              - ref: values
                repoURL: 'https://github.com/second-front/argocd-test.git'
                targetRevision: main
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              managedNamespaceMetadata:
                labels:
                  istio-injection: enabled
              syncOptions:
                - CreateNamespace=true
                - Validate=false
                - RespectIgnoreDifferences=true
  metricsServer:
    sourceType: helmRepo
    enabled: auto
    values:
      args:
      - --kubelet-insecure-tls

  minioOperator:
    sourceType: helmRepo
    enabled: true